name: noxvus
description: NOXVUS Tools Platform by @xzrinx
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  geolocator: ^11.0.0
  intl: ^0.19.0
  flutter_animate: ^4.5.0
  url_launcher: ^6.2.5
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true